### ISSUE TITLE
after a while the api stops responding.

### ISSUE THREAD

**Issue by ev4ndropc** [joaomirandasa/w2api#1]
I deployed this api on my digitalocean server and after a few hours it stops sending messages when I make the request. it gives the status: true but does not send.

**Comment by joaomirandasa** [comment]
Could you give more information about it? did you deploy using Docker or zip/package?  @ev4ndropc

**Comment by ev4ndropc** [comment]
> Could you give more information about it? did you deploy using Docker or zip/package? @ev4ndropc

Vou falar em português porque vi que você é brasileiro kkk.

Eu fiz o deploy dos arquivos do git, se quiser te passo o link da api do meu deploy para você fazer testes caso necessário

**Comment by joaomirandasa** [comment]
It's better to spoke in en for other users can understand if necessary in future, 

First of all, when this happen, you could check endpoint  "/{instance}/{masterKey}/isConnected" and get an screencapture from your instance to check whats going on inside of your application browser over "/{instance}/{masterKey}/screenCapture"

Share results to keep helping you.

**Comment by ev4ndropc** [comment]
> It's better to spoke in en for other users can understand if necessary in future,
> 
> First of all, when this happen, you could check endpoint "/{instance}/{masterKey}/isConnected" and get an screencapture from your instance to check whats going on inside of your application browser over "/{instance}/{masterKey}/screenCapture"
> 
> Share results to keep helping you.

So you're giving this error.

```
{
status: false,
err: "Wrong token authentication"
}
```

This is the link `http://app.automatiz.me:8000/83430/j19ksi1mim1lksm12213/screenCapture`

**Comment by joaomirandasa** [comment]
Let's start from begginig, i already have knew about issues with longer elapsed time since instance started, it's not the best solution but you could prepare an CRON task to reboot your instance, stop your node env and start again, this way you will clean all trash information, and script auto-start by himself once alredy connected before

**Comment by impozzible** [comment]
I don't have this issue yet, my bot has been running for a couple of days. 

Secondly how to reboot instance with cron

**Comment by joaomirandasa** [comment]
Você pode configurar um reinicio usando tarefas cronológicas do servidor hospedeiro.

Verifique os exemplos: https://www.geeksforgeeks.org/crontab-in-linux-with-examples/
