### ISSUE TITLE
Webhook Not Working

### ISSUE THREAD

**Issue by impozzible** [joaomirandasa/w2api#2]
Posts are not been posted to the webhook, I tested with requestcatcher.com

**Comment by impozzible** [comment]
@joaomirandasa kindly check here

**Comment by joaomirandasa** [comment]
✅ **Fix:**  
Check last update into[ #e87a77b](https://github.com/joaomirandasa/w2api/commit/c647f80779c489345889346d76bb641945f97418)

**Comment by impozzible** [comment]
I cloned the repo again, and now it's stuck at initializing whatsapp

**Comment by joaomirandasa** [comment]
New updates be provided by one of libraries used into W2API, his maintainer release a new version right now!

Old Version:
`"dependencies": {
    "async": "^3.2.0",
    "download-file": "^0.1.5",
    "moment": "^2.24.0",
    "sulla-hotfix": "^1.8.0",
    "total.js": "^3.4.0"
  }`

New Version:
`"dependencies": {
    "async": "^3.2.0",
    "download-file": "^0.1.5",
    "moment": "^2.24.0",
    "sulla-hotfix": "^1.8.22",
    "total.js": "^3.4.0"
  }`

Inside package.json
Please **clone repo again now** or run `npm update`!

**Comment by impozzible** [comment]
Ok now working, but currently I cannot message contact not in my chat list again,

**Comment by joaomirandasa** [comment]
Yes! you cant send message to who dosn't send you anything before - it's an security middleware to avoid this library be used for spam. Please read section [Legal](https://github.com/joaomirandasa/w2api#legal)
@impozzible that's all! Thank you for your issue reports. Thanks in advance for close when done.

**Comment by impozzible** [comment]
Thanks, Is it possible to receive file from webhook?

**Comment by joaomirandasa** [comment]
@impozzible Yes! It's possible but you will receive this as base64 file enconded, probably to use you need to save into a folder and provide external link. You already try to receive it?

**Comment by impozzible** [comment]
Yes I tried it , but am not getting anything in the webhook
