### ISSUE TITLE
Send contact is not defined

### ISSUE THREAD

**Issue by andretasty** [joaomirandasa/w2api#3]
I download the library and run with >node debug.js and i get the error:

sendContact is not defined. 

What i'm doing wrong?

**Comment by joaomirandasa** [comment]
@andretasty  It's not defined yet, became necessary improve my instance backend. Do you alredy create something to PR?

**Comment by daries** [comment]
<img width="572" alt="Screen Shot 2020-03-31 at 08 11 36" src="https://user-images.githubusercontent.com/3004414/77976468-482c4100-7327-11ea-91ef-685f066dcec0.png">
I am also the same error

**Comment by impozzible** [comment]
Comment that out, and it will.work

**Comment by impozzible** [comment]
<img width="731" alt="Screenshot 2020-03-31 at 2 18 10 AM" src="https://user-images.githubusercontent.com/30698707/77976837-f5866100-72f5-11ea-93d3-7e404eb9f3ad.png">
It's inside controllers/api.js

**Comment by daries** [comment]
ok thanks

> Comment that out, and it will.work

ok thanks

**Comment by joaomirandasa** [comment]
I will prepare an update allowing to send contact information, soon will be available

**Comment by joaomirandasa** [comment]
This route is now available! Please check new version, 
Thank You.
