### ISSUE TITLE
404: Not Found

### ISSUE THREAD

**Issue by intec-id** [joaomirandasa/w2api#4]
I'm trying curl to send message by post json to address http://localhost:8000/83430/sendMessage?token=j19ksi1mim1lksm12213 but got en error so I'm trying to access address http://localhost:8000/83430/sendMessage?token=j19ksi1mim1lksm12213 got status **404: Not Found**

**Comment by impozzible** [comment]
Share your config

**Comment by intec-id** [comment]
//WhatsApp Configurations		
instance            : 83430
webhook             : http://localhost/w2api.php
token               : j19ksi1mim1lksm12213
masterKey           : w2apiisthebestlibrary

**Comment by joaomirandasa** [comment]
@intec-id did you try use examples into Postman? Best way to do that is create your request into postman, edit your variables and export code directly from Postman. 

Try this and share with us.

**Comment by intec-id** [comment]
Done, thanks.

> @intec-id did you try use examples into Postman? Best way to do that is create your request into postman, edit your variables and export code directly from Postman.
> 
> Try this and share with us.

Done, work perfect. many thanks
