### ISSUE TITLE
Running Multiple Instance

### ISSUE THREAD

**Issue by impozzible** [joaomirandasa/w2api#5]
How can I run mutliple instance of script with different configs

**Comment by joaomirandasa** [comment]
The best way to do that is running inside Docker Containers, i already started to prepare this for docker but not completed yet, i didn't have enough time..

**Comment by impozzible** [comment]
Oh I see, I already did a temporary fix to the script.to support multiple instance, when will the docker image be ready, thanks for the great job

**Comment by chiragkhichadiya** [comment]
> Oh I see, I already did a temporary fix to the script.to support multiple instance, when will the docker image be ready, thanks for the great job

What changes did you make in script to run multiple instances?
