### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by lemessenoire** [joaomirandasa/w2api#6]
Hi, I am configuring w2api on AWS EC2 Linux Ami instance with NVM Node v 10.19.

 When I start the application everything seems normal, but when looking for the URL http: // localhost: 8000/83430 / qrcode I get a 404 error and I can't find the path.

 This is my configuration:

name                            : W2API
author                          : João Vitor Miranda Santos
version                         : 0.0.1

//WhatsApp Configurations		
instance						: 83430
webhook							: https://abc123.requestcatcher.com/test
token							: ugictxugo7gugif
masterKey						: igi7icufjf

**Comment by joaomirandasa** [comment]
Take some attention to enviroment you are running, if you setup this library on cloud, like AWS EC2, you cant reach this instance over localhost, because its not running locally, rigth?! So to access this, you shold use instance public IP Address, attention to firewall rules into EC2 too.

**Comment by lemessenoire** [comment]
Hello, I understand your response, the server is an EC2 instance, but when trying to enter the URL http://xxx.xxx.xxx:8000/8343/QRCODE, the 404 Not Found error message appears. 

I am making a chatbot to avoid the cropless infodemia, in addition, I made some models of AI and DL for the detection of false news and prevent the spread of them. 

Next I want to ask you some questions, please help me answer them, because I urgently need to enable this chatbot. As I told him, I have an error when starting the server, I can not see any of the URLs, especially the QRCODE.

1. At this time, the operation of the route / QRcode is not active?, I ask this question because the QR code is charging me on the command line terminal screen.

2. If scanning the QR code from the terminal, W2API will let me see now the routes?, That is, from the URL http://xxx.xxx.xxx:8000/8343/qrcode? For me, its collaboration is very important, as I told him, it is not a business project, but a tool against the Coreavirus Incodemia. 

3. Each time whatsapp Web is disconnected, should I scan the code?, When the session is saved, how long active tough time? If you want, I can enable a server so you can see all my configuration and check what I am saying. 

My concern is that the objective of this project is to make it public on April 13 or no later than 20 and with these inconveniences it will be impossible for me to fulfill that goal.

If you want we can speak for a more private medium and I send you the access data and I solve any questions you have. Thank you, a hug.

**Comment by joaomirandasa** [comment]
Please meet me in Discord: https://discord.gg/CJRTPv
